"""Initial schema: users and client_reports

Revision ID: 147496921eed
Revises: 
Create Date: 2026-09-06 16:37:23.428084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147496921eed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('client_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.Column('form_json', sa.Text(), nullable=False),
    sa.Column('scorecard_json', sa.Text(), nullable=False),
    sa.Column('insights_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_reports_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_reports_user_id'))

    op.drop_table('client_reports')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
