"""Add account lockout fields to users

Revision ID: db74a3830402
Revises: fb73997782fe
Create Date: 2026-09-08 07:30:09.842245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db74a3830402'
down_revision = 'fb73997782fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: hand-adjusted after autogenerate. The raw autogenerated version
    # used `nullable=False` with no server_default, which fails against any
    # table that already has rows (confirmed by testing against a
    # pre-existing user row): SQLite and Postgres both reject adding a
    # NOT NULL column with no default to a non-empty table. server_default
    # backfills existing rows to 0; the Python-side default (in models.py)
    # still governs new inserts going forward.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
