"""Add email_verified to users

Revision ID: fb73997782fe
Revises: 147496921eed
Create Date: 2026-09-07 09:30:56.587199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb73997782fe'
down_revision = '147496921eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # HAND-FIXED (September 2026, after a real production failure): the
    # original autogenerated version used nullable=False with no default,
    # which fails on Postgres (and any DB) the moment the table has any
    # existing rows — confirmed for real against Render's production
    # Postgres: "column 'email_verified' of relation 'users' contains
    # null values". This is the exact same class of bug already caught
    # and fixed in the account-lockout migration (db74a3830402) during
    # local testing — this older migration predates that audit and was
    # never checked for the same issue, which is exactly how it reached
    # production undetected. server_default=sa.false() backfills existing
    # rows to False; the Python-side default in models.py still governs
    # new inserts going forward.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
